### PR TITLE
CT-2872 | Change of CRI causing resetting config - bug

### PR DESCRIPTION
**Pull request by RafalOzogJudopay**
As summary of my investigation:

1. The config gets reset when we come back from the 'child' screen to Settings screen. The state variables gets reset to defaults (as 'useEffect' is not re-triggered in this case), and function handleSettingsChange is then overriding our memory-stored settings with default set of values.

2. To prevent this we should persist or re-set the state correctly, before handleSettingsChange is executed. 

I tried to use StackOverFlow suggested solutions with useEffect, and useEffectFocus (this one is run also when we re-open the screen), but it's executed too late for us (later than handleSettingsChange callback).

I also tried to force the settings to be re-read from the handleSettingsChange callback before the rest of its code is executed - but also in this case settings were not ready on time, as they're being set asynchronously atm.

Another way of handling this would be to use Redux to handle state persistance, but as the whole architecture in this screen is kind of messy (writing and reading methods are called multiple times for no reason), I would suggest to go with the quick fix for now, and remake the screen in the future.

### CODE REVIEW

**Review by eugenezhernakov — APPROVED** [review]

**Comment by stefan-tudor** [comment]
> Another way of handling this would be to use Redux to handle state persistence,

We should keep things as simple as possible. Redux will make things much more complex, and it's an overkill for this sample app.

Most probably, bugs are caused by the misuse of some hooks somewhere.

**Comment by stefan-tudor** [comment]
@RafalOzogJudopay, the actual problem here is that we do not wait for `handleSettingsChange(path, item.id)` in `useSingleSelectionTableListener` to complete before navigating to the previous screen.

In addition, `writeSettingsToStorage` is slow and causes many delays in the UI. We need to move away from this library or refactor the persistence of settings data.

**Review by stefan-tudor — CHANGES_REQUESTED** [review]
Let's catch up on this.

**Review by stefan-tudor — APPROVED** [review]

**Review by RafalOzogJudopay — COMMENTED** [review]
Nice code!

Simplifies settings storage quite well. I don't have comments about the code, giving it some testing now, and will approve if no issues found.

**Pull request merged**
